config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :cards
  resources :users,         only: [:new, :create, :edit, :update]
  resources :user_sessions, only: [:new, :create, :destroy]
  post 'check_card',      to: 'pages#check_card'
  get  'login',           to: 'user_sessions#new', as: :login
  post 'logout',          to: 'user_sessions#destroy', as: :logout
  post 'oauth/callback',  to: 'oauths#callback'
  get  'oauth/callback',  to: 'oauths#callback'
  get  'oauth/:provider', to: 'oauths#oauth', as: :auth_at_provider
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/card.rb
class Card < ApplicationRecord
  attr_accessor :image_cache
  before_create :set_review_date
  mount_uploader :image, ImageUploader

  validates :original_text, :translated_text, presence: true
  validate :cards_text_cannot_match

  belongs_to :user

  protected

  def set_review_date
    self.review_date = Time.now + 3.days
  end

  def cards_text_cannot_match
    unless translated_text.nil?
      if self.original_text.downcase == self.translated_text.downcase
        errors.add(:translated_text, 'Перевод должен отличаться от оригинала')
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :cards, dependent: :destroy
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, length: {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, alert: 'Только для зарегистрированных пользователей'
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  def index
    @cards = current_user.cards.order('review_date')
  end

  def new
    @card = Card.new
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to @card, notice: 'Карточка создана'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @card.update(card_params)
      redirect_to @card, notice: 'Готово'
    else
      render :edit
    end
  end

  def destroy
    @card.destroy
    redirect_to root_path, notice: 'Карточка удалена'
  end

  private

  def set_card
    @card = current_user.cards.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:original_text, :translated_text, :review_date)
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_filter :require_login

  def oauth
    login_at(auth_params[:provider])
  end

  def callback
    provider = auth_params[:provider]
    if @user = login_from(provider)
      redirect_to root_url
      notice: ("Вы вошли спомощью #{provider} аккаунта",
                provider: provider.titleize)
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        redirect_to root_url
        notice: ("Вы вошли спомощью #{provider} аккаунта",
                  provider: provider.titleize)
      rescue
        redirect_to user_sessions_path
        alert: ("Вход из аккаунта #{provider.titleize} не выполнен",
                 provider: provider.titleize)
      end
    end
  end

  private

  def auth_params
    params.permit(:code, :provider)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @card = CheckCard.call
  end

  def check_card
    @card = Card.find(params[:id])
    result = CheckCard.answer(@card, answer_params[:answer])
    redirect_to root_url, notice: result
  end

  private

  def answer_params
    params.permit(:answer)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    if current_user
      redirect_to root_url
    else
      @user = User.new
    end
  end

  def create
    if @user = login(session_params[:email], session_params[:password])
      redirect_back_or_to root_url, notice: 'С возвращением!'
    else
      flash.now[:alert] = 'Email или пароль не совпадают'
      render :new
    end
  end

  def destroy
    logout
    redirect_to(root_url, notice: 'До встречи!')
  end

  private

  def session_params
    params.require(:user_sessions).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:edit, :update]

  def new
    if current_user
      redirect_to root_url
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_url, notice: 'Пользователь успешно создан'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def set_user
    @user = User.find(params[:id])
    redirect_to root_url unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_card.html.erb
<div class="random-card">
  <div class="row">
    <div class="col-md-6">
      <div class="card-deck-wrapper">
        <div class="card-deck">
          <div class="card">
            <div class="card-block">
              Перевод (English): <%= @card.translated_text %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
  <%= render 'shared/msg', object: @card %>
  <div class="row">
    <div class="col-md-6">
      <%= f.input :original_text, label: 'Оригинальный текст (Deutsch):' %>
      <br>
    </div>
    <div class="col-md-6">
      <%= f.input :translated_text, label: 'Перевод (English):' %>
      <br>
    </div>
    <div class="col-md-7">
      <%= image_tag(@card.image_url) if @card.image? %>
      <%= f.file_field :image %>
      <%= f.hidden_field :image_cache %>
    </div>
    <br>
    <br>
    <div class="col-md-6">
      <div class="actions">
        <%= f.button :submit, 'Готово', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/cards/edit.html.erb
<div class="card card-default">
  <div class="card-header">
    Внести изменения
  </div>
  <div class="card-block">
    <%= render 'form' %>
  </div>
</div>

app/views/cards/index.html.erb
<div class="row">
  <% @cards.each do |card| %>
    <div class="col-xl-4 col-lg-6">
      <div class="card-deck-wrapper">
        <div class="card-deck">
          <div class="card">
            <div class="card-header">
              <%= link_to card do %>
                Оригинальный текст (Deutsch): <%= card.original_text %>
              <% end %>
            </div>
            <div class="card-block">
              Перевод (English): <%= card.translated_text %>
            </div>
            <div class="card-footer">
              Дата проверки: <%= card.review_date.strftime('%d/%m/%Y') %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cards/new.html.erb
<%= render 'form' %>

app/views/cards/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="card-deck-wrapper">
      <div class="card-deck">
        <div class="card">
          <div class="card-header">
            Оригинальный текст (Deutsch): <%= @card.original_text %>
          </div>
          <div class="card-block">
            <%= image_tag(@card.image_url) if @card.image? %>
            Перевод (English): <%= @card.translated_text %>
          </div>
          <div class="card-footer">
            Дата проверки: <%= @card.review_date.strftime('%d/%m/%Y') %>&nbsp;
            <%= render 'shared/links' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>
    <div class="container">
      <div class="row">
        <div class="col-md-6 push-md-6">
          <ul class="navigation-links">
            <% if current_user %>
              <li>
                <%= link_to 'Все карточки', cards_path %>
              </li>
              <li>
                <%= link_to 'Добавить карточку', new_card_path %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="col-md-6 pull-md-6">
          <h1>Флэшкарточкер</h1>
        </div>
      </div>
      <br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_form.html.erb
<h6>Вспомните оригинальный текст, соответствующий переводу:</h6>
<br>
<%= form_tag check_card_path do %>
  <div class="row">
    <div class="input-group">
      <%= hidden_field_tag 'id', @card.id %>
      <%= text_field_tag 'answer', nil, placeholder: 'Ваш вариант',
                                        class: 'form-control' %>
      <span class="input-group-btn">
        <%= submit_tag 'Готово', class: 'btn btn-primary', name: 'Submit' %>
      </span>
    </div>
  </div>
<% end %>

app/views/pages/index.html.erb
<section>
  <p class="description">
    Первый в мире удобный менеджер флеш-карточек. Именно так.
  </p>
  <% if @card %>
    <%= render 'cards/card' %>
    <div class="col-md-6">
      <%= render 'form' %>
    </div>
  <% end %>
</section>

app/views/shared/_links.html.erb
<%= link_to edit_card_path(@card) do %>
  <%= fa_icon('pencil') %>
<% end %>
&nbsp;
<%= link_to card_path(@card), data: {:confirm => 'Удаляем карточку?'},
                              method: :delete do %>
  <%= fa_icon('times') %>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      <% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_msg.html.erb
<% unless object.errors.empty? %>
  <script type="text/javascript">
    <% object.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button"
          data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to root_url, class: 'navbar-brand' do %>
    Флэшкарточкер
  <% end %>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      <li class="nav-item active">
        <%= link_to root_url, class: 'nav-link' do %>
          Главная
        <% end %>
      </li>
      <% if current_user %>
        <li class="nav-item">
          <%= link_to edit_user_path(current_user.id), class: 'nav-link' do %>
            Редактировать профиль
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to :logout, method: :post, class: 'nav-link' do %>
            Выйти
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_path, class: 'nav-link' do %>
            Зарегистрироваться
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to auth_at_provider_path(provider: :github),
                      class: 'nav-link' do %>
            Войти через Github
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to :login, class: 'nav-link' do %>
            Войти
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/user_sessions/_form.html.erb
<%= simple_form_for :user_sessions, {url: user_sessions_path} do |f| %>
  <div class="form-group col-md-6">
    <%= f.input :email, label: 'Email', class: 'form-control' %>
    <%= f.input :password, label: 'Пароль', class: 'form-control' %>
    <%= f.submit 'Войти', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h5>Вход</h5>
<br>
<%= render 'form' %>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= render 'shared/msg', object: @user %>
  <div class="form-group col-md-6">
    <%= f.input :email, label: 'Email', class: 'form-control' %>
    <%= f.input :password, label: 'Пароль', class: 'form-control' %>
    <%= f.submit 'Готово', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h5>Редактировать профиль</h5>
<br>
<%= render 'form' %>
<%= link_to 'На главную', root_url %>

app/views/users/new.html.erb
<h5>Регистрация</h5>
<br>
<%= render 'form' %>
<%= link_to 'На главную', root_url %>